name: we_travel
description: It is an application that fully supports your travel. Currently under development.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  salomon_bottom_bar: ^3.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  firebase_auth: ^4.1.2
  firebase_messaging: ^14.1.0
  lottie: ^1.4.2
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.2.0

# UI
  gap: ^2.0.0
  modal_bottom_sheet: ^2.1.2

# Navigator
  go_router: ^5.1.5

# State
  hooks_riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  pedantic_mono: any
  riverpod_generator: ^1.0.6
flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
